export const MeilisearchSettingsTable = {
    collection: "meilisearch_settings",
    meta: {
        collection: "meilisearch_settings",
        icon: "search",
        note: null,
        display_template: null,
        singleton: true,
        translations: null,
        archive_field: null,
        archive_app_filter: true,
        archive_value: null,
        unarchive_value: null,
        sort_field: null,
        accountability: "all",
        color: null,
        item_duplication_fields: null,
        sort: null,
        group: null,
        collapse: "open",
        preview_url: null,
        versioning: false,
    },
    schema: {
        schema: "public",
        name: "meilisearch_settings",
        comment: null,
    },
    fields: [
        {
            collection: "meilisearch_settings",
            field: "id",
            type: "integer",
            schema: {
                name: "id",
                table: "meilisearch_settings",
                schema: "public",
                data_type: "integer",
                is_nullable: false,
                generation_expression: null,
                default_value:
                    "nextval('meilisearch_settings_id_seq'::regclass)",
                is_generated: false,
                max_length: null,
                comment: null,
                numeric_precision: 32,
                numeric_scale: 0,
                is_unique: true,
                is_primary_key: true,
                has_auto_increment: true,
                foreign_key_schema: null,
                foreign_key_table: null,
                foreign_key_column: null,
            },
            meta: {
                collection: "meilisearch_settings",
                field: "id",
                special: null,
                interface: "input",
                options: null,
                display: null,
                display_options: null,
                readonly: true,
                hidden: true,
                sort: 1,
                width: "full",
                translations: null,
                note: null,
                conditions: null,
                required: false,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
        {
            collection: "meilisearch_settings",
            field: "user_created",
            type: "uuid",
            schema: {
                name: "user_created",
                table: "meilisearch_settings",
                schema: "public",
                data_type: "uuid",
                is_nullable: true,
                generation_expression: null,
                default_value: null,
                is_generated: false,
                max_length: null,
                comment: null,
                numeric_precision: null,
                numeric_scale: null,
                is_unique: false,
                is_primary_key: false,
                has_auto_increment: false,
                foreign_key_schema: "public",
                foreign_key_table: "directus_users",
                foreign_key_column: "id",
            },
            meta: {
                collection: "meilisearch_settings",
                field: "user_created",
                special: ["user-created"],
                interface: "select-dropdown-m2o",
                options: {
                    template:
                        "{{avatar.$thumbnail}} {{first_name}} {{last_name}}",
                },
                display: "user",
                display_options: null,
                readonly: true,
                hidden: true,
                sort: 2,
                width: "half",
                translations: null,
                note: null,
                conditions: null,
                required: false,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
        {
            collection: "meilisearch_settings",
            field: "date_created",
            type: "timestamp",
            schema: {
                name: "date_created",
                table: "meilisearch_settings",
                schema: "public",
                data_type: "timestamp with time zone",
                is_nullable: true,
                generation_expression: null,
                default_value: null,
                is_generated: false,
                max_length: null,
                comment: null,
                numeric_precision: null,
                numeric_scale: null,
                is_unique: false,
                is_primary_key: false,
                has_auto_increment: false,
                foreign_key_schema: null,
                foreign_key_table: null,
                foreign_key_column: null,
            },
            meta: {
                collection: "meilisearch_settings",
                field: "date_created",
                special: ["date-created"],
                interface: "datetime",
                options: null,
                display: "datetime",
                display_options: {
                    relative: true,
                },
                readonly: true,
                hidden: true,
                sort: 3,
                width: "half",
                translations: null,
                note: null,
                conditions: null,
                required: false,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
        {
            collection: "meilisearch_settings",
            field: "user_updated",
            type: "uuid",
            schema: {
                name: "user_updated",
                table: "meilisearch_settings",
                schema: "public",
                data_type: "uuid",
                is_nullable: true,
                generation_expression: null,
                default_value: null,
                is_generated: false,
                max_length: null,
                comment: null,
                numeric_precision: null,
                numeric_scale: null,
                is_unique: false,
                is_primary_key: false,
                has_auto_increment: false,
                foreign_key_schema: "public",
                foreign_key_table: "directus_users",
                foreign_key_column: "id",
            },
            meta: {
                collection: "meilisearch_settings",
                field: "user_updated",
                special: ["user-updated"],
                interface: "select-dropdown-m2o",
                options: {
                    template:
                        "{{avatar.$thumbnail}} {{first_name}} {{last_name}}",
                },
                display: "user",
                display_options: null,
                readonly: true,
                hidden: true,
                sort: 4,
                width: "half",
                translations: null,
                note: null,
                conditions: null,
                required: false,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
        {
            collection: "meilisearch_settings",
            field: "date_updated",
            type: "timestamp",
            schema: {
                name: "date_updated",
                table: "meilisearch_settings",
                schema: "public",
                data_type: "timestamp with time zone",
                is_nullable: true,
                generation_expression: null,
                default_value: null,
                is_generated: false,
                max_length: null,
                comment: null,
                numeric_precision: null,
                numeric_scale: null,
                is_unique: false,
                is_primary_key: false,
                has_auto_increment: false,
                foreign_key_schema: null,
                foreign_key_table: null,
                foreign_key_column: null,
            },
            meta: {
                collection: "meilisearch_settings",
                field: "date_updated",
                special: ["date-updated"],
                interface: "datetime",
                options: null,
                display: "datetime",
                display_options: {
                    relative: true,
                },
                readonly: true,
                hidden: true,
                sort: 5,
                width: "half",
                translations: null,
                note: null,
                conditions: null,
                required: false,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
        {
            collection: "meilisearch_settings",
            field: "host",
            type: "string",
            schema: {
                name: "host",
                table: "meilisearch_settings",
                schema: "public",
                data_type: "character varying",
                is_nullable: true,
                generation_expression: null,
                default_value: null,
                is_generated: false,
                max_length: 255,
                comment: null,
                numeric_precision: null,
                numeric_scale: null,
                is_unique: false,
                is_primary_key: false,
                has_auto_increment: false,
                foreign_key_schema: null,
                foreign_key_table: null,
                foreign_key_column: null,
            },
            meta: {
                collection: "meilisearch_settings",
                field: "host",
                special: null,
                interface: "input",
                options: {
                    trim: true,
                    placeholder: "https://meilisearch-endpoint.net",
                },
                display: null,
                display_options: null,
                readonly: false,
                hidden: false,
                sort: 7,
                width: "half",
                translations: null,
                note: null,
                conditions: null,
                required: true,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
        {
            collection: "meilisearch_settings",
            field: "api_key",
            type: "string",
            schema: {
                name: "api_key",
                table: "meilisearch_settings",
                schema: "public",
                data_type: "character varying",
                is_nullable: true,
                generation_expression: null,
                default_value: null,
                is_generated: false,
                max_length: 255,
                comment: null,
                numeric_precision: null,
                numeric_scale: null,
                is_unique: false,
                is_primary_key: false,
                has_auto_increment: false,
                foreign_key_schema: null,
                foreign_key_table: null,
                foreign_key_column: null,
            },
            meta: {
                collection: "meilisearch_settings",
                field: "api_key",
                special: null,
                interface: "input",
                options: {
                    trim: true,
                    placeholder: "hZGaN8cL4nW2x7L_qz9HcPg1PJCcjuMa4431QELxN1Q",
                },
                display: null,
                display_options: null,
                readonly: false,
                hidden: false,
                sort: 8,
                width: "half",
                translations: null,
                note: null,
                conditions: null,
                required: true,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
        {
            collection: "meilisearch_settings",
            field: "collections_configuration",
            type: "json",
            schema: {
                name: "collections_configuration",
                table: "meilisearch_settings",
                schema: "public",
                data_type: "json",
                is_nullable: true,
                generation_expression: null,
                default_value: [],
                is_generated: false,
                max_length: null,
                comment: null,
                numeric_precision: null,
                numeric_scale: null,
                is_unique: false,
                is_primary_key: false,
                has_auto_increment: false,
                foreign_key_schema: null,
                foreign_key_table: null,
                foreign_key_column: null,
            },
            meta: {
                collection: "meilisearch_settings",
                field: "collections_configuration",
                special: ["cast-json"],
                interface: "input-code",
                options: null,
                display: null,
                display_options: null,
                readonly: false,
                hidden: false,
                sort: 9,
                width: "full",
                translations: null,
                note: null,
                conditions: null,
                required: false,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
        {
            collection: "meilisearch_settings",
            field: "notice-np8y8a",
            type: "alias",
            schema: null,
            meta: {
                collection: "meilisearch_settings",
                field: "notice-np8y8a",
                special: ["alias", "no-data"],
                interface: "presentation-notice",
                options: {
                    color: "info",
                    text: "Due to limitations with hooks, remember to restart Directus after updating the settings.",
                },
                display: null,
                display_options: null,
                readonly: false,
                hidden: false,
                sort: 6,
                width: "full",
                translations: null,
                note: null,
                conditions: null,
                required: false,
                group: null,
                validation: null,
                validation_message: null,
            },
        },
    ],
};
